### PR TITLE
Added localsettings

### PR DESCRIPTION
**Pull request by FlyveHest**
Added a localsettings.lua file to make it easier to keep local settings changes when updating from GIT repo, and also did the same for server.cfg

Updated warmoji submodule, as I got errors when checking out the project.

### CODE REVIEW

**Comment by warxander** [comment]
Hi,

Thank you very much for PR!

However, I have some questions, and the most important one is why we need `localsettings` when we have `git rebase`, which is in my opinion more convenient in terms of keeping sources up-to-date?

**Comment by FlyveHest** [comment]
The localsettings is actually more so you, as a server admin, have an easier overlook of what settings you have changed, and if the devs (you :) decide to add settings, you don't risk getting a merge conflict in the base settings.

Same idea with server.cfg, even though that will probably not be updated.

git rebase is not really meant to be used for you to keep a local copy of a file from a repo out of sync.

**Comment by warxander** [comment]
You need to keep your local settings in actual state, so if something will be removed or renamed - you will know it through merge conflicts. How are you supposed to do this with `localsettings` file?

**Comment by FlyveHest** [comment]
If its removed, it doesn't really matter, all that would happen is that you have a settings variable that is never used.

The same goes for renaming, worst case is that your changes are not reflected on your server, but any change to the settings should be mentioned in a changelog regardless, at least, thats what I would expect, and then you would rename them in your local settings also.

Merge conflicts are never nice to resolve, and even more so for people that aren't developers, but are just using the repository as an easy means to get the latest version.

Also, if you download the repo as a ZIP file, you can just extract without thinking about overwriting your settings changes, if all changes are done in settings.lua, and you unpack a never version, the risk of overwriting your changes are high. (I have done that more than once ;)

**Comment by warxander** [comment]
Please make warmoji submodule update as a separate commit (+ use `1.1` tag).

**Comment by FlyveHest** [comment]
I'll remove the warmoji change from my PR, maybe you could update it in master?  I got a strange tree reference error when trying to check out with submodules.

**Comment by warxander** [comment]
Ok

**Comment by FlyveHest** [comment]
Submodule update is reverted

**Comment by warxander** [comment]
Improved and became a part of new update.

**Pull request closed without merging**
